### ISSUE TITLE
Bug need help:  Delete All POIs after delete any one POI from these auto-catched POIs, errors will show.

### ISSUE THREAD

**Issue by diamond2nv** [Ulm-IQO/qudi#515] opened 2019-05-19 13:18 UTC
## *What* is affected by this bug?

- Win10 64bit
- Win10 . 1809
- Qudi branch - POI_autocatch
- gui//poimanger//poimangui.py
- logic//poi_manager_logic.py

## *When* does this occur?

- After "Auto POIs" and Delete any one POI from these auto-catched POIs, then Delete All POIs.

## *Where* on the platform does it happen?

```
Traceback (most recent call last):
  File "F:\GitLab\qudi\gui\poimanager\poimangui.py", line 703, in update_active_poi
    active_poi_pos = self.poimanagerlogic().get_poi_position(name)
  File "F:\GitLab\qudi\logic\poi_manager_logic.py", line 687, in get_poi_position
    return self._roi.get_poi_position(name)
  File "F:\GitLab\qudi\logic\poi_manager_logic.py", line 169, in get_poi_p
KeyError: 'No POI with name "poi_20190519205716389310" found in POI list.'
```
## *How* do we replicate the issue?

- Qudi branch - POI_autocatch
- POI Manager GUI 
    1. "Auto POIs" : catch lots POIs
    1.  Delete any one POI from these auto-catched POIs
    1. Delete All POIs. and errors (error number = number of left POIs ) will show. But all POIs would be deleted.

## Expected behavior (i.e. solution)

- After "Auto POIs" and Delete any one POI from these auto-catched POIs, at last Delete All POIs will be OK with no error show.

**Comment by liuyanulm** [comment] 2019-05-24 16:01
Hi @diamond2nv ,
Many thanks for finding the bug.
It was caused by active_poi settings. 
Now it is fixed with the latest update.

**Closed** 2019-05-27 02:09 UTC
